### ISSUE TITLE
it throws error when I start it

### ISSUE THREAD

**Issue by adxxtya** [PlytonRexus/chain-reaction#12]
Refused to apply style from 'http://localhost:7000/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.   play:1
 
GET http://localhost:7000/lib/socket.io.slim.js net::ERR_ABORTED 404 (Not Found)   play:21

GET http://localhost:7000/io.js 404 (Not Found)   play:22

GET http://localhost:7000/index.js net::ERR_ABORTED 404 (Not Found)   play:23

GET http://localhost:7000/chat.js net::ERR_ABORTED 404 (Not Found)   play:24

GET http://localhost:7000/explosion.mp3 404 (Not Found)   play:25

GET http://localhost:7000/io.js net::ERR_ABORTED 404 (Not Found)   play:26

GET http://localhost:7000/index.js net::ERR_ABORTED 404 (Not Found)   play:27

GET http://localhost:7000/chat.js net::ERR_ABORTED 404 (Not Found)     play:28

**Comment by PlytonRexus** [comment]
Hi!
Sorry for the late reply. I really don't maintain this repo anymore. And would really like contributions to make this work. If you can help, feel free to send pulls!

Applied a minor fix. Could you check now? @adxxtya

**Comment by adxxtya** [comment]
oh it works perfectly sorry for replying late too, it works now, thanks a lot
