### ISSUE TITLE
Undo is not usable

### ISSUE THREAD

**Issue by PlytonRexus** [PlytonRexus/chain-reaction#7]
The undo button is disabled because it creates problems in the online multiplayer mode. I don't remember what the problem was but it should be something simple.

**Comment by fandok** [comment]
can i take a look on it?

**Comment by PlytonRexus** [comment]
Sure, go ahead. I suppose the code is a bit messed up but shouldn't be too difficult to navigate.On 1 Oct 2020 18:14, Fandika Okdiba <notifications@github.com> wrote:
can i take a look on it?

**Comment by prateek1998** [comment]
I can help you in resolving this issue.

**Comment by PlytonRexus** [comment]
#9 cleared here.

**Comment by PlytonRexus** [comment]
Hi Divine,

A lot of thanks for your email and call.

My GitHub user ID is @plytonrexus<https://github.com/plytonrexus>, and the email address used to sign up was ***@***.******@***.***> (this email is also set as primary on Github).

I tried following the instructions you sent me but got stuck on the first step. I can't seem to get a Student Developer Pack active on emails other than my school email (screenshots below).
[cid:cf3021b4-93a3-4508-9ecc-828949cf8ad8]




[cid:dcfdbc91-2c36-4c7f-8286-b568ce5d7a99]

And, if I try to log in to Azure (here)<https://signup.azure.com/studentverification?offerType=1>, this is what happens (recording below).

azure_github_signup-2022-02-16.mp4<https://1drv.ms/u/s!AkJC4jj9zCltwF40Zsynybl9NHYQ>
________________________________
From: Divine ***@***.***>
Sent: Tuesday, February 15, 2022 7:27 AM
To: Microsoft Support ***@***.***>; Mihir Jichkar ***@***.***>
Subject: RE: Case 2202120060000088  Your question was s... - TrackingID#2202120060000088

Hi Mihir,

Good day.

Greetings from Microsoft. This is Divine and I am more than happy to assist you with your concern.

I appreciate your interest in Azure for students. As I understand, you are having trouble registering to Azure for students using your Github account. To better assist you, kindly provide the below details:

DETAILS NEEDED
Email address used to sign up to Github
Github UserID

Also, please provide the recording or step by step screenshot of the below instructions. Please ensure that the recording/screenshot captures every step as the Tier 2 team cannot proceed with the investigation if the recording or details are incomplete/incorrect.

To record, please check the instructions here - Windows<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F22878%2Fwindows-10-record-steps&data=04%7C01%7Cv-abcaas%40microsoft.com%7Cd6d5800343fc4d34f42908d8ca03cabe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481464996413651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Wppuz%2F%2FbZftsYZwvpOtnnWe%2FmVUzH%2BYNSQngZSkICNU%3D&reserved=0> - Mac<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.apple.com%2Fen-us%2FHT208721&data=04%7C01%7Cv-abcaas%40microsoft.com%7Cd6d5800343fc4d34f42908d8ca03cabe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481464996423642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HPt5ztwTapi4J8SvMmn8JF%2B8RjgvQk31RcxKil9uH%2FY%3D&reserved=0>. Please use InPrivate browser or Incognito.

For step by step screenshots, please ensure that it captures the whole page (including URL).

1. Go to https://education.github.com/discount_requests/student_application to check your approved UserID.

***@***.***
2. On the middle part of the above page, please ensure that you choose the same email address that you used to sign up for GIthub in “What email do you use for school?” If you used your personal email address to sign up for Github, please choose the personal email address.

***@***.***

3. Fill out the information here and click on continue. Please ensure the recording captures the error message (if any).
***@***.***

4. Then visit https://github.com/login<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flogin&data=04%7C01%7Cv-abcaas%40microsoft.com%7C925e2e5f4aa84f53ef5308d9038f310f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637544735886271018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZF7WjjO4UT1PYNdHKTfKQm1zZQkKfg6VTWTHrteQeY0%3D&reserved=0>
5. Log in using your GIthub userID and not email address.
6. Click on your profile in the upper right hand corner then click on "Settings"
***@***.***
7. Make sure same email address that you used to sign up is listed under "Emails" and that it is chosen as the “Primary email”
***@***.***
8. Then go to - https://signup.azure.com/studentverification?offerType=1<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsignup.azure.com%2Fstudentverification%3FofferType%3D1&data=02%7C01%7Cv-abcaas%40microsoft.com%7Cf1636106b47f495801a608d7ddad4314%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637221608555477536&sdata=%2BzJM3nuD8Izf3IRQ2sn1H69n7enAUgYkeg4cPAzJtwI%3D&reserved=0>.
9. Click on "Sign in with your Github"

***@***.***

10. If you get stuck in the verification page, kindly show the options you see available. Ensure that it captures your email address on the top right of the page.

11. Choose Github option. If you get an error message that your student status is not verified, please click on "here."

***@***.***

I look forward to your response. Should you have further questions or concerns, do not hesitate to reply to this email.

Thank you for supporting Microsoft. Have a great one.


Best Regards,
Divine
Microsoft Subscriptions Service Center APGC Support
(Microsoft Azure for Student)
Email:  Submit Online request<https://scanmail.trustwave.com/?c=10354&d=o-344c8i6ouYnBdp1nOwiYIXt0bmPmZiWvJ0y6Lxgw&u=https%3a%2f%2fazureforeducation%2emicrosoft%2ecom%2fen-us%2finstitutions%2fContact>
Operating hours: 9:00am – 6:00pm (Monday – Friday, except Public Holiday)



------------------- Original Message -------------------
From: Microsoft Support ***@***.***>;
Received: Sat Feb 12 2022 19:51:09 GMT+0800 (GMT+08:00)
To: Mihir Jichkar ***@***.***>;
Subject: Case 2202120060000088  Your question was succe... - TrackingID#2202120060000088


[Microsoft]

Support

Thank you. Your question was successfully submitted to Microsoft Support.

Please keep in mind: microsoftsupport.com and microsoft.com are both valid email domains used for communications related to your support request.

Incident title: Cannot access Azure for Students via Github Student Developer Pack
Support request number: 2202120060000088
Severity rating:        C
Expect response within:
8
Contact preference:
Email
Name:   Mihir Jichkar
Email address:
***@***.***
Contact numbers:
7030607235

Thank you,
Microsoft Support


Additional Information

Product: Developer, Student and Startup Programs/Azure for Education/Assigning or Activating Benefits


This message from Microsoft is an important part of a program, service, or product that you or your company purchased or participates in. Microsoft respects your privacy. Please read our Privacy Statement<http://azure.microsoft.com/support/trust-center/privacy/>.


One Microsoft Way, Redmond, WA 98052 USA


[Microsoft]
